
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snpstats`=list(
        `type`="software", 
        `author`="Moreno V, et al.", 
        `year`=2006, 
        `title`="SNPStats: analysis of association studies", 
        `publisher`="https://www.snpstats.net", 
        `url`="https://www.snpstats.net"), 
    `bioinfo`=list(
        `type`="journal", 
        `author`="Sole, X., Guino, E., Valls, J., Iniesta, R., Moreno, V.", 
        `year`=2006, 
        `title`="SNPStats: a web tool for the analysis of association studies", 
        `publisher`="Bioinformatics 22(15):1928-1929 https://doi.org/10.1093/bioinformatics/btl268", 
        `url`="https://doi.org/10.1093/bioinformatics/btl268"))
