
# This file is automatically generated, you probably don't want to edit this

snpAssocOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpAssocOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            response = NULL,
            snps = NULL,
            covariates = NULL,
            responseType = "auto",
            snpAssoc = TRUE,
            modelCodominant = TRUE,
            modelDominant = FALSE,
            modelRecessive = FALSE,
            modelOverdominant = FALSE,
            modelLogAdditive = FALSE,
            ciWidth = 95,
            showAIC = FALSE,
            snpInteraction = FALSE,
            interactionType = "multiplicative",
            showInteractionTable = TRUE,
            showInteractionAdjVars = FALSE,
            showStratByCovariate = FALSE,
            showStratByGenotype = FALSE,
            showCrossClassTable = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpAssoc",
                requiresData=TRUE,
                ...)

            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..snps <- jmvcore::OptionVariables$new(
                "snps",
                snps,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..responseType <- jmvcore::OptionList$new(
                "responseType",
                responseType,
                options=list(
                    "auto",
                    "binary",
                    "quantitative"),
                default="auto")
            private$..snpAssoc <- jmvcore::OptionBool$new(
                "snpAssoc",
                snpAssoc,
                default=TRUE)
            private$..modelCodominant <- jmvcore::OptionBool$new(
                "modelCodominant",
                modelCodominant,
                default=TRUE)
            private$..modelDominant <- jmvcore::OptionBool$new(
                "modelDominant",
                modelDominant,
                default=FALSE)
            private$..modelRecessive <- jmvcore::OptionBool$new(
                "modelRecessive",
                modelRecessive,
                default=FALSE)
            private$..modelOverdominant <- jmvcore::OptionBool$new(
                "modelOverdominant",
                modelOverdominant,
                default=FALSE)
            private$..modelLogAdditive <- jmvcore::OptionBool$new(
                "modelLogAdditive",
                modelLogAdditive,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..showAIC <- jmvcore::OptionBool$new(
                "showAIC",
                showAIC,
                default=FALSE)
            private$..snpInteraction <- jmvcore::OptionBool$new(
                "snpInteraction",
                snpInteraction,
                default=FALSE)
            private$..interactionType <- jmvcore::OptionList$new(
                "interactionType",
                interactionType,
                options=list(
                    "multiplicative",
                    "conditional_on_covar",
                    "conditional_on_snp"),
                default="multiplicative")
            private$..showInteractionTable <- jmvcore::OptionBool$new(
                "showInteractionTable",
                showInteractionTable,
                default=TRUE)
            private$..showInteractionAdjVars <- jmvcore::OptionBool$new(
                "showInteractionAdjVars",
                showInteractionAdjVars,
                default=FALSE)
            private$..showStratByCovariate <- jmvcore::OptionBool$new(
                "showStratByCovariate",
                showStratByCovariate,
                default=FALSE)
            private$..showStratByGenotype <- jmvcore::OptionBool$new(
                "showStratByGenotype",
                showStratByGenotype,
                default=FALSE)
            private$..showCrossClassTable <- jmvcore::OptionBool$new(
                "showCrossClassTable",
                showCrossClassTable,
                default=FALSE)

            self$.addOption(private$..response)
            self$.addOption(private$..snps)
            self$.addOption(private$..covariates)
            self$.addOption(private$..responseType)
            self$.addOption(private$..snpAssoc)
            self$.addOption(private$..modelCodominant)
            self$.addOption(private$..modelDominant)
            self$.addOption(private$..modelRecessive)
            self$.addOption(private$..modelOverdominant)
            self$.addOption(private$..modelLogAdditive)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..showAIC)
            self$.addOption(private$..snpInteraction)
            self$.addOption(private$..interactionType)
            self$.addOption(private$..showInteractionTable)
            self$.addOption(private$..showInteractionAdjVars)
            self$.addOption(private$..showStratByCovariate)
            self$.addOption(private$..showStratByGenotype)
            self$.addOption(private$..showCrossClassTable)
        }),
    active = list(
        response = function() private$..response$value,
        snps = function() private$..snps$value,
        covariates = function() private$..covariates$value,
        responseType = function() private$..responseType$value,
        snpAssoc = function() private$..snpAssoc$value,
        modelCodominant = function() private$..modelCodominant$value,
        modelDominant = function() private$..modelDominant$value,
        modelRecessive = function() private$..modelRecessive$value,
        modelOverdominant = function() private$..modelOverdominant$value,
        modelLogAdditive = function() private$..modelLogAdditive$value,
        ciWidth = function() private$..ciWidth$value,
        showAIC = function() private$..showAIC$value,
        snpInteraction = function() private$..snpInteraction$value,
        interactionType = function() private$..interactionType$value,
        showInteractionTable = function() private$..showInteractionTable$value,
        showInteractionAdjVars = function() private$..showInteractionAdjVars$value,
        showStratByCovariate = function() private$..showStratByCovariate$value,
        showStratByGenotype = function() private$..showStratByGenotype$value,
        showCrossClassTable = function() private$..showCrossClassTable$value),
    private = list(
        ..response = NA,
        ..snps = NA,
        ..covariates = NA,
        ..responseType = NA,
        ..snpAssoc = NA,
        ..modelCodominant = NA,
        ..modelDominant = NA,
        ..modelRecessive = NA,
        ..modelOverdominant = NA,
        ..modelLogAdditive = NA,
        ..ciWidth = NA,
        ..showAIC = NA,
        ..snpInteraction = NA,
        ..interactionType = NA,
        ..showInteractionTable = NA,
        ..showInteractionAdjVars = NA,
        ..showStratByCovariate = NA,
        ..showStratByGenotype = NA,
        ..showCrossClassTable = NA)
)

snpAssocResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpAssocResults",
    inherit = jmvcore::Group,
    active = list(
        validationMsg = function() private$.items[["validationMsg"]],
        snpResults = function() private$.items[["snpResults"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SNP Association Analysis",
                refs=list(
                    "snpstats",
                    "bioinfo"))
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsg",
                title="",
                visible=FALSE))
            self$add(jmvcore::Array$new(
                options=options,
                name="snpResults",
                title="SNP Association Results",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        typingRate = function() private$.items[["typingRate"]],
                        assocTable = function() private$.items[["assocTable"]],
                        interactionResults = function() private$.items[["interactionResults"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Html$new(
                                options=options,
                                name="typingRate",
                                title="",
                                visible=TRUE))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="assocTable",
                                title="Association with Response",
                                visible="(snpAssoc && (modelCodominant || modelDominant || modelRecessive || modelOverdominant || modelLogAdditive))",
                                columns=list(
                                    list(
                                        `name`="model", 
                                        `title`="Model", 
                                        `type`="text"),
                                    list(
                                        `name`="genotype", 
                                        `title`="Genotype", 
                                        `type`="text"),
                                    list(
                                        `name`="stat0", 
                                        `title`="Group 0", 
                                        `type`="text"),
                                    list(
                                        `name`="stat1", 
                                        `title`="Group 1", 
                                        `type`="text"),
                                    list(
                                        `name`="effect", 
                                        `title`="OR / \u03B2", 
                                        `type`="number", 
                                        `format`="zto"),
                                    list(
                                        `name`="ciLow", 
                                        `title`="Lower CI", 
                                        `type`="number", 
                                        `format`="zto"),
                                    list(
                                        `name`="ciHigh", 
                                        `title`="Upper CI", 
                                        `type`="number", 
                                        `format`="zto"),
                                    list(
                                        `name`="pval", 
                                        `title`="P-value", 
                                        `type`="number", 
                                        `format`="zto"),
                                    list(
                                        `name`="AIC", 
                                        `title`="AIC", 
                                        `type`="number", 
                                        `format`="zto", 
                                        `visible`=FALSE),
                                    list(
                                        `name`="BIC", 
                                        `title`="BIC", 
                                        `type`="number", 
                                        `format`="zto", 
                                        `visible`=FALSE))))
                            self$add(jmvcore::Array$new(
                                options=options,
                                name="interactionResults",
                                title="Interaction Results",
                                visible="(snpInteraction)",
                                template=R6::R6Class(
                                    inherit = jmvcore::Group,
                                    active = list(
                                        interactionTable = function() private$.items[["interactionTable"]],
                                        stratByCovariateHeading = function() private$.items[["stratByCovariateHeading"]],
                                        stratByCovariate = function() private$.items[["stratByCovariate"]],
                                        stratByGenotypeHeading = function() private$.items[["stratByGenotypeHeading"]],
                                        stratByGenotype = function() private$.items[["stratByGenotype"]],
                                        crossClassHeading = function() private$.items[["crossClassHeading"]],
                                        crossClassTable = function() private$.items[["crossClassTable"]]),
                                    private = list(),
                                    public=list(
                                        initialize=function(options) {
                                            super$initialize(
                                                options=options,
                                                name="undefined",
                                                title="$key")
                                            self$add(jmvcore::Table$new(
                                                options=options,
                                                name="interactionTable",
                                                title="SNP \u00D7 Covariate Interaction",
                                                visible="(snpInteraction && showInteractionTable)",
                                                columns=list(
                                                    list(
                                                        `name`="model", 
                                                        `title`="Model", 
                                                        `type`="text"),
                                                    list(
                                                        `name`="term", 
                                                        `title`="Term", 
                                                        `type`="text"),
                                                    list(
                                                        `name`="effect", 
                                                        `title`="OR / \u03B2", 
                                                        `type`="number", 
                                                        `format`="zto"),
                                                    list(
                                                        `name`="ciLow", 
                                                        `title`="Lower CI", 
                                                        `type`="number", 
                                                        `format`="zto"),
                                                    list(
                                                        `name`="ciHigh", 
                                                        `title`="Upper CI", 
                                                        `type`="number", 
                                                        `format`="zto"),
                                                    list(
                                                        `name`="pval", 
                                                        `title`="P-value", 
                                                        `type`="number", 
                                                        `format`="zto"),
                                                    list(
                                                        `name`="AIC", 
                                                        `title`="AIC", 
                                                        `type`="number", 
                                                        `format`="zto", 
                                                        `visible`=FALSE),
                                                    list(
                                                        `name`="BIC", 
                                                        `title`="BIC", 
                                                        `type`="number", 
                                                        `format`="zto", 
                                                        `visible`=FALSE))))
                                            self$add(jmvcore::Html$new(
                                                options=options,
                                                name="stratByCovariateHeading",
                                                title="",
                                                visible="(snpInteraction && showStratByCovariate)"))
                                            self$add(jmvcore::Array$new(
                                                options=options,
                                                name="stratByCovariate",
                                                title="",
                                                visible="(snpInteraction && showStratByCovariate)",
                                                template=jmvcore::Table$new(
                                                    options=options,
                                                    title="$key",
                                                    columns=list(
                                                        list(
                                                            `name`="genotype", 
                                                            `title`="Genotype", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="stat0", 
                                                            `title`="Group 0", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="stat1", 
                                                            `title`="Group 1", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="effect", 
                                                            `title`="OR / \u03B2", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="ciLow", 
                                                            `title`="Lower CI", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="ciHigh", 
                                                            `title`="Upper CI", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="pval", 
                                                            `title`="P-value", 
                                                            `type`="number", 
                                                            `format`="zto")))))
                                            self$add(jmvcore::Html$new(
                                                options=options,
                                                name="stratByGenotypeHeading",
                                                title="",
                                                visible="(snpInteraction && showStratByGenotype)"))
                                            self$add(jmvcore::Array$new(
                                                options=options,
                                                name="stratByGenotype",
                                                title="",
                                                visible="(snpInteraction && showStratByGenotype)",
                                                template=jmvcore::Table$new(
                                                    options=options,
                                                    title="$key",
                                                    columns=list(
                                                        list(
                                                            `name`="level", 
                                                            `title`="Level", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="stat0", 
                                                            `title`="Group 0", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="stat1", 
                                                            `title`="Group 1", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="effect", 
                                                            `title`="OR / \u03B2", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="ciLow", 
                                                            `title`="Lower CI", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="ciHigh", 
                                                            `title`="Upper CI", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="pval", 
                                                            `title`="P-value", 
                                                            `type`="number", 
                                                            `format`="zto")))))
                                            self$add(jmvcore::Html$new(
                                                options=options,
                                                name="crossClassHeading",
                                                title="",
                                                visible="(snpInteraction && showCrossClassTable)"))
                                            self$add(jmvcore::Array$new(
                                                options=options,
                                                name="crossClassTable",
                                                title="",
                                                visible="(snpInteraction && showCrossClassTable)",
                                                template=jmvcore::Table$new(
                                                    options=options,
                                                    title="$key",
                                                    columns=list(
                                                        list(
                                                            `name`="genotype", 
                                                            `title`="Genotype", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="stat0", 
                                                            `title`="Group 0", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="stat1", 
                                                            `title`="Group 1", 
                                                            `type`="text"),
                                                        list(
                                                            `name`="effect", 
                                                            `title`="OR / \u03B2", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="ciLow", 
                                                            `title`="Lower CI", 
                                                            `type`="number", 
                                                            `format`="zto"),
                                                        list(
                                                            `name`="ciHigh", 
                                                            `title`="Upper CI", 
                                                            `type`="number", 
                                                            `format`="zto")))))}))$new(options=options)))}))$new(options=options)))}))

snpAssocBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpAssocBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpAssoc",
                version = c(0,2,0),
                options = options,
                results = snpAssocResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' SNP Association Analysis
#'
#' 
#' @param data [object Object]
#' @param response .
#' @param snps .
#' @param covariates .
#' @param responseType .
#' @param snpAssoc .
#' @param modelCodominant .
#' @param modelDominant .
#' @param modelRecessive .
#' @param modelOverdominant .
#' @param modelLogAdditive .
#' @param ciWidth .
#' @param showAIC .
#' @param snpInteraction .
#' @param interactionType .
#' @param showInteractionTable .
#' @param showInteractionAdjVars .
#' @param showStratByCovariate .
#' @param showStratByGenotype .
#' @param showCrossClassTable .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$validationMsg} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$snpResults} \tab \tab \tab \tab \tab Per-SNP association results \cr
#' }
#'
#' @export
snpAssoc <- function(
    data,
    response,
    snps,
    covariates = NULL,
    responseType = "auto",
    snpAssoc = TRUE,
    modelCodominant = TRUE,
    modelDominant = FALSE,
    modelRecessive = FALSE,
    modelOverdominant = FALSE,
    modelLogAdditive = FALSE,
    ciWidth = 95,
    showAIC = FALSE,
    snpInteraction = FALSE,
    interactionType = "multiplicative",
    showInteractionTable = TRUE,
    showInteractionAdjVars = FALSE,
    showStratByCovariate = FALSE,
    showStratByGenotype = FALSE,
    showCrossClassTable = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpAssoc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if ( ! missing(snps)) snps <- jmvcore::resolveQuo(jmvcore::enquo(snps))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(response), response, NULL),
            `if`( ! missing(snps), snps, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- snpAssocOptions$new(
        response = response,
        snps = snps,
        covariates = covariates,
        responseType = responseType,
        snpAssoc = snpAssoc,
        modelCodominant = modelCodominant,
        modelDominant = modelDominant,
        modelRecessive = modelRecessive,
        modelOverdominant = modelOverdominant,
        modelLogAdditive = modelLogAdditive,
        ciWidth = ciWidth,
        showAIC = showAIC,
        snpInteraction = snpInteraction,
        interactionType = interactionType,
        showInteractionTable = showInteractionTable,
        showInteractionAdjVars = showInteractionAdjVars,
        showStratByCovariate = showStratByCovariate,
        showStratByGenotype = showStratByGenotype,
        showCrossClassTable = showCrossClassTable)

    analysis <- snpAssocClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

