
# This file is automatically generated, you probably don't want to edit this

snpDescOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpDescOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            response = NULL,
            snps = NULL,
            covariates = NULL,
            responseType = "auto",
            subpop = FALSE,
            covDesc = FALSE,
            rmSnpMissing = FALSE,
            snpSummary = TRUE,
            allFreq = FALSE,
            genoFreq = FALSE,
            hweTest = FALSE,
            showMissing = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpDesc",
                requiresData=TRUE,
                ...)

            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..snps <- jmvcore::OptionVariables$new(
                "snps",
                snps,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..responseType <- jmvcore::OptionList$new(
                "responseType",
                responseType,
                options=list(
                    "auto",
                    "binary",
                    "quantitative",
                    "categorical"),
                default="auto")
            private$..subpop <- jmvcore::OptionBool$new(
                "subpop",
                subpop,
                default=FALSE)
            private$..covDesc <- jmvcore::OptionBool$new(
                "covDesc",
                covDesc,
                default=FALSE)
            private$..rmSnpMissing <- jmvcore::OptionBool$new(
                "rmSnpMissing",
                rmSnpMissing,
                default=FALSE)
            private$..snpSummary <- jmvcore::OptionBool$new(
                "snpSummary",
                snpSummary,
                default=TRUE)
            private$..allFreq <- jmvcore::OptionBool$new(
                "allFreq",
                allFreq,
                default=FALSE)
            private$..genoFreq <- jmvcore::OptionBool$new(
                "genoFreq",
                genoFreq,
                default=FALSE)
            private$..hweTest <- jmvcore::OptionBool$new(
                "hweTest",
                hweTest,
                default=FALSE)
            private$..showMissing <- jmvcore::OptionBool$new(
                "showMissing",
                showMissing,
                default=FALSE)

            self$.addOption(private$..response)
            self$.addOption(private$..snps)
            self$.addOption(private$..covariates)
            self$.addOption(private$..responseType)
            self$.addOption(private$..subpop)
            self$.addOption(private$..covDesc)
            self$.addOption(private$..rmSnpMissing)
            self$.addOption(private$..snpSummary)
            self$.addOption(private$..allFreq)
            self$.addOption(private$..genoFreq)
            self$.addOption(private$..hweTest)
            self$.addOption(private$..showMissing)
        }),
    active = list(
        response = function() private$..response$value,
        snps = function() private$..snps$value,
        covariates = function() private$..covariates$value,
        responseType = function() private$..responseType$value,
        subpop = function() private$..subpop$value,
        covDesc = function() private$..covDesc$value,
        rmSnpMissing = function() private$..rmSnpMissing$value,
        snpSummary = function() private$..snpSummary$value,
        allFreq = function() private$..allFreq$value,
        genoFreq = function() private$..genoFreq$value,
        hweTest = function() private$..hweTest$value,
        showMissing = function() private$..showMissing$value),
    private = list(
        ..response = NA,
        ..snps = NA,
        ..covariates = NA,
        ..responseType = NA,
        ..subpop = NA,
        ..covDesc = NA,
        ..rmSnpMissing = NA,
        ..snpSummary = NA,
        ..allFreq = NA,
        ..genoFreq = NA,
        ..hweTest = NA,
        ..showMissing = NA)
)

snpDescResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpDescResults",
    inherit = jmvcore::Group,
    active = list(
        validationMsgSNP = function() private$.items[["validationMsgSNP"]],
        validationMsgGeno = function() private$.items[["validationMsgGeno"]],
        covDescGroup = function() private$.items[["covDescGroup"]],
        snpSummaryTablesGroup = function() private$.items[["snpSummaryTablesGroup"]],
        snpResults = function() private$.items[["snpResults"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SNP Descriptive",
                refs=list(
                    "snpstats",
                    "bioinfo"))
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsgSNP",
                title="",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsgGeno",
                title="",
                visible=FALSE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    covDescTable = function() private$.items[["covDescTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="covDescGroup",
                            title="Covariate Descriptives")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="covDescTable",
                            title="Covariate Summary",
                            columns=list(
                                list(
                                    `name`="variable", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="level", 
                                    `title`="Level", 
                                    `type`="text"),
                                list(
                                    `name`="stat_overall", 
                                    `title`="Overall", 
                                    `type`="text"),
                                list(
                                    `name`="stat_g0", 
                                    `title`="Group 0", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="stat_g1", 
                                    `title`="Group 1", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="stat_g2", 
                                    `title`="Group 2", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="stat_g3", 
                                    `title`="Group 3", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="stat_g4", 
                                    `title`="Group 4", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="stat_g5", 
                                    `title`="Group 5", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="stat_g6", 
                                    `title`="Group 6", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="stat_g7", 
                                    `title`="Group 7", 
                                    `type`="text", 
                                    `visible`=FALSE),
                                list(
                                    `name`="pval", 
                                    `title`="P-value", 
                                    `type`="number", 
                                    `format`="zto", 
                                    `visible`=FALSE))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    snpSummaryTable = function() private$.items[["snpSummaryTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="snpSummaryTablesGroup",
                            title="SNP Descriptive")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="snpSummaryTable",
                            title="SNP Summary Table",
                            visible="(snpSummary)",
                            columns=list(
                                list(
                                    `name`="snp", 
                                    `title`="SNP", 
                                    `type`="text"),
                                list(
                                    `name`="alleles", 
                                    `title`="Alleles (A/B)", 
                                    `type`="text"),
                                list(
                                    `name`="group", 
                                    `title`="Group", 
                                    `type`="text"),
                                list(
                                    `name`="n", 
                                    `title`="N", 
                                    `type`="integer"),
                                list(
                                    `name`="missing", 
                                    `title`="Missing", 
                                    `type`="integer"),
                                list(
                                    `name`="maf", 
                                    `title`="MAF (B)", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="genoCounts", 
                                    `title`="AA / AB / BB", 
                                    `type`="text"),
                                list(
                                    `name`="hwePval", 
                                    `title`="HWE p-value", 
                                    `type`="number", 
                                    `format`="zto"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="snpResults",
                title="SNP Results",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        typingRate = function() private$.items[["typingRate"]],
                        allFreqTable = function() private$.items[["allFreqTable"]],
                        genoFreqTable = function() private$.items[["genoFreqTable"]],
                        hweTable = function() private$.items[["hweTable"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Html$new(
                                options=options,
                                name="typingRate",
                                title="",
                                visible="(allFreq || genoFreq || hweTest)"))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="allFreqTable",
                                title="Allele Frequencies",
                                visible="(allFreq)",
                                columns=list(
                                    list(
                                        `name`="allele", 
                                        `title`="Allele", 
                                        `type`="text"),
                                    list(
                                        `name`="stat", 
                                        `title`="N (%)", 
                                        `type`="text"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="genoFreqTable",
                                title="Genotype Frequencies",
                                visible="(genoFreq)",
                                columns=list(
                                    list(
                                        `name`="genotype", 
                                        `title`="Genotype", 
                                        `type`="text"),
                                    list(
                                        `name`="stat", 
                                        `title`="N (%)", 
                                        `type`="text"),
                                    list(
                                        `name`="responseStat", 
                                        `title`="Response (mean\u00B1SE)", 
                                        `type`="text", 
                                        `visible`=FALSE))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="hweTable",
                                title="Hardy-Weinberg Equilibrium",
                                visible="(hweTest)",
                                columns=list(
                                    list(
                                        `name`="group", 
                                        `title`="Group", 
                                        `type`="text"),
                                    list(
                                        `name`="n11", 
                                        `title`="AA", 
                                        `type`="integer"),
                                    list(
                                        `name`="n12", 
                                        `title`="AB", 
                                        `type`="integer"),
                                    list(
                                        `name`="n22", 
                                        `title`="BB", 
                                        `type`="integer"),
                                    list(
                                        `name`="missing", 
                                        `title`="Missing", 
                                        `type`="integer", 
                                        `visible`=FALSE),
                                    list(
                                        `name`="pval", 
                                        `title`="P-value", 
                                        `type`="number", 
                                        `format`="zto"))))}))$new(options=options)))}))

snpDescBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpDescBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpDesc",
                version = c(0,2,0),
                options = options,
                results = snpDescResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' SNP Descriptive
#'
#' 
#' @param data [object Object]
#' @param response .
#' @param snps .
#' @param covariates .
#' @param responseType .
#' @param subpop .
#' @param covDesc .
#' @param rmSnpMissing .
#' @param snpSummary .
#' @param allFreq .
#' @param genoFreq .
#' @param hweTest .
#' @param showMissing .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$validationMsgSNP} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$validationMsgGeno} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$covDescGroup$covDescTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$snpSummaryTablesGroup$snpSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$snpResults} \tab \tab \tab \tab \tab Per-SNP descriptive results \cr
#' }
#'
#' @export
snpDesc <- function(
    data,
    response = NULL,
    snps,
    covariates = NULL,
    responseType = "auto",
    subpop = FALSE,
    covDesc = FALSE,
    rmSnpMissing = FALSE,
    snpSummary = TRUE,
    allFreq = FALSE,
    genoFreq = FALSE,
    hweTest = FALSE,
    showMissing = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpDesc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if ( ! missing(snps)) snps <- jmvcore::resolveQuo(jmvcore::enquo(snps))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(response), response, NULL),
            `if`( ! missing(snps), snps, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- snpDescOptions$new(
        response = response,
        snps = snps,
        covariates = covariates,
        responseType = responseType,
        subpop = subpop,
        covDesc = covDesc,
        rmSnpMissing = rmSnpMissing,
        snpSummary = snpSummary,
        allFreq = allFreq,
        genoFreq = genoFreq,
        hweTest = hweTest,
        showMissing = showMissing)

    analysis <- snpDescClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

