
# This file is automatically generated, you probably don't want to edit this

snpLDHaploOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpLDHaploOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            response = NULL,
            snps = NULL,
            covariates = NULL,
            responseType = "auto",
            ldAnalysis = FALSE,
            ldMatrix = FALSE,
            ldMetric = "r2",
            ldPlot = FALSE,
            haploFreq = FALSE,
            haploFreqMin = 0.01,
            subpop = FALSE,
            haploAssoc = FALSE,
            ciWidth = 95,
            haploInteraction = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpLDHaplo",
                requiresData=TRUE,
                ...)

            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..snps <- jmvcore::OptionVariables$new(
                "snps",
                snps,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..responseType <- jmvcore::OptionList$new(
                "responseType",
                responseType,
                options=list(
                    "auto",
                    "binary",
                    "quantitative"),
                default="auto")
            private$..ldAnalysis <- jmvcore::OptionBool$new(
                "ldAnalysis",
                ldAnalysis,
                default=FALSE)
            private$..ldMatrix <- jmvcore::OptionBool$new(
                "ldMatrix",
                ldMatrix,
                default=FALSE)
            private$..ldMetric <- jmvcore::OptionList$new(
                "ldMetric",
                ldMetric,
                options=list(
                    "r2",
                    "Dprime",
                    "D"),
                default="r2")
            private$..ldPlot <- jmvcore::OptionBool$new(
                "ldPlot",
                ldPlot,
                default=FALSE)
            private$..haploFreq <- jmvcore::OptionBool$new(
                "haploFreq",
                haploFreq,
                default=FALSE)
            private$..haploFreqMin <- jmvcore::OptionNumber$new(
                "haploFreqMin",
                haploFreqMin,
                min=0,
                max=0.5,
                default=0.01)
            private$..subpop <- jmvcore::OptionBool$new(
                "subpop",
                subpop,
                default=FALSE)
            private$..haploAssoc <- jmvcore::OptionBool$new(
                "haploAssoc",
                haploAssoc,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..haploInteraction <- jmvcore::OptionBool$new(
                "haploInteraction",
                haploInteraction,
                default=FALSE)

            self$.addOption(private$..response)
            self$.addOption(private$..snps)
            self$.addOption(private$..covariates)
            self$.addOption(private$..responseType)
            self$.addOption(private$..ldAnalysis)
            self$.addOption(private$..ldMatrix)
            self$.addOption(private$..ldMetric)
            self$.addOption(private$..ldPlot)
            self$.addOption(private$..haploFreq)
            self$.addOption(private$..haploFreqMin)
            self$.addOption(private$..subpop)
            self$.addOption(private$..haploAssoc)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..haploInteraction)
        }),
    active = list(
        response = function() private$..response$value,
        snps = function() private$..snps$value,
        covariates = function() private$..covariates$value,
        responseType = function() private$..responseType$value,
        ldAnalysis = function() private$..ldAnalysis$value,
        ldMatrix = function() private$..ldMatrix$value,
        ldMetric = function() private$..ldMetric$value,
        ldPlot = function() private$..ldPlot$value,
        haploFreq = function() private$..haploFreq$value,
        haploFreqMin = function() private$..haploFreqMin$value,
        subpop = function() private$..subpop$value,
        haploAssoc = function() private$..haploAssoc$value,
        ciWidth = function() private$..ciWidth$value,
        haploInteraction = function() private$..haploInteraction$value),
    private = list(
        ..response = NA,
        ..snps = NA,
        ..covariates = NA,
        ..responseType = NA,
        ..ldAnalysis = NA,
        ..ldMatrix = NA,
        ..ldMetric = NA,
        ..ldPlot = NA,
        ..haploFreq = NA,
        ..haploFreqMin = NA,
        ..subpop = NA,
        ..haploAssoc = NA,
        ..ciWidth = NA,
        ..haploInteraction = NA)
)

snpLDHaploResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpLDHaploResults",
    inherit = jmvcore::Group,
    active = list(
        validationMsg = function() private$.items[["validationMsg"]],
        ldGroup = function() private$.items[["ldGroup"]],
        haploGroup = function() private$.items[["haploGroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LD and Haplotype Analysis",
                refs=list(
                    "snpstats",
                    "bioinfo"))
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsg",
                title="",
                visible=FALSE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    ldTable = function() private$.items[["ldTable"]],
                    ldMatrixTable = function() private$.items[["ldMatrixTable"]],
                    ldPlotImage = function() private$.items[["ldPlotImage"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ldGroup",
                            title="Linkage Disequilibrium")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="ldTable",
                            title="Pairwise LD",
                            visible="(ldAnalysis)",
                            columns=list(
                                list(
                                    `name`="snp1", 
                                    `title`="SNP 1", 
                                    `type`="text"),
                                list(
                                    `name`="snp2", 
                                    `title`="SNP 2", 
                                    `type`="text"),
                                list(
                                    `name`="r2", 
                                    `title`="r\u00B2", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="Dprime", 
                                    `title`="D'", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="D", 
                                    `title`="D", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pval", 
                                    `title`="P-value", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="ldMatrixTable",
                            title="LD Matrix",
                            visible="(ldMatrix)",
                            columns=list(
                                list(
                                    `name`="snp", 
                                    `title`="SNP", 
                                    `type`="text"))))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="ldPlotImage",
                            title="LD Heatmap",
                            visible="(ldPlot)",
                            renderFun=".render_ld_plot",
                            width=500,
                            height=450))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    haploFreqTable = function() private$.items[["haploFreqTable"]],
                    haploAssocTable = function() private$.items[["haploAssocTable"]],
                    haploInteractionTable = function() private$.items[["haploInteractionTable"]],
                    haploCondCovarTable = function() private$.items[["haploCondCovarTable"]],
                    haploCondHaploTable = function() private$.items[["haploCondHaploTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="haploGroup",
                            title="Haplotype Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="haploFreqTable",
                            title="Haplotype Frequencies",
                            visible="(haploFreq)",
                            columns=list(
                                list(
                                    `name`="haplotype", 
                                    `title`="Haplotype", 
                                    `type`="text"),
                                list(
                                    `name`="freq", 
                                    `title`="Frequency", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="freq_g0", 
                                    `title`="Group 0", 
                                    `type`="number", 
                                    `format`="zto", 
                                    `visible`=FALSE),
                                list(
                                    `name`="freq_g1", 
                                    `title`="Group 1", 
                                    `type`="number", 
                                    `format`="zto", 
                                    `visible`=FALSE))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="haploAssocTable",
                            title="Haplotype Association",
                            visible="(haploAssoc)",
                            columns=list(
                                list(
                                    `name`="haplotype", 
                                    `title`="Haplotype", 
                                    `type`="text"),
                                list(
                                    `name`="freq", 
                                    `title`="Frequency", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="effect", 
                                    `title`="OR / \u03B2", 
                                    `type`="number"),
                                list(
                                    `name`="ciLow", 
                                    `title`="Lower CI", 
                                    `type`="number"),
                                list(
                                    `name`="ciHigh", 
                                    `title`="Upper CI", 
                                    `type`="number"),
                                list(
                                    `name`="pval", 
                                    `title`="P-value", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="haploInteractionTable",
                            title="Haplotype \u00D7 Covariate Interaction (cross-classification)",
                            visible="(haploInteraction)",
                            columns=list(
                                list(
                                    `name`="term", 
                                    `title`="Haplotype", 
                                    `type`="text"),
                                list(
                                    `name`="freq", 
                                    `title`="Frequency", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="haploCondCovarTable",
                            title="Haplotype Effect within Covariate Levels",
                            visible="(haploInteraction)",
                            columns=list(
                                list(
                                    `name`="term", 
                                    `title`="Haplotype", 
                                    `type`="text"),
                                list(
                                    `name`="freq", 
                                    `title`="Frequency", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="haploCondHaploTable",
                            title="Covariate Effect within Haplotypes",
                            visible="(haploInteraction)",
                            columns=list(
                                list(
                                    `name`="term", 
                                    `title`="Haplotype", 
                                    `type`="text"),
                                list(
                                    `name`="freq", 
                                    `title`="Frequency", 
                                    `type`="number", 
                                    `format`="zto"))))}))$new(options=options))}))

snpLDHaploBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpLDHaploBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpLDHaplo",
                version = c(0,2,0),
                options = options,
                results = snpLDHaploResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' LD and Haplotype Analysis
#'
#' 
#' @param data [object Object]
#' @param response .
#' @param snps .
#' @param covariates .
#' @param responseType .
#' @param ldAnalysis .
#' @param ldMatrix .
#' @param ldMetric .
#' @param ldPlot .
#' @param haploFreq .
#' @param haploFreqMin .
#' @param subpop .
#' @param haploAssoc .
#' @param ciWidth .
#' @param haploInteraction .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$validationMsg} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ldGroup$ldTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ldGroup$ldMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ldGroup$ldPlotImage} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$haploGroup$haploFreqTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$haploGroup$haploAssocTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$haploGroup$haploInteractionTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$haploGroup$haploCondCovarTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$haploGroup$haploCondHaploTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
snpLDHaplo <- function(
    data,
    response = NULL,
    snps,
    covariates = NULL,
    responseType = "auto",
    ldAnalysis = FALSE,
    ldMatrix = FALSE,
    ldMetric = "r2",
    ldPlot = FALSE,
    haploFreq = FALSE,
    haploFreqMin = 0.01,
    subpop = FALSE,
    haploAssoc = FALSE,
    ciWidth = 95,
    haploInteraction = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpLDHaplo requires jmvcore to be installed (restart may be required)")

    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if ( ! missing(snps)) snps <- jmvcore::resolveQuo(jmvcore::enquo(snps))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(response), response, NULL),
            `if`( ! missing(snps), snps, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- snpLDHaploOptions$new(
        response = response,
        snps = snps,
        covariates = covariates,
        responseType = responseType,
        ldAnalysis = ldAnalysis,
        ldMatrix = ldMatrix,
        ldMetric = ldMetric,
        ldPlot = ldPlot,
        haploFreq = haploFreq,
        haploFreqMin = haploFreqMin,
        subpop = subpop,
        haploAssoc = haploAssoc,
        ciWidth = ciWidth,
        haploInteraction = haploInteraction)

    analysis <- snpLDHaploClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

