
# This file is automatically generated, you probably don't want to edit this

snpPGSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            idCol = NULL,
            snpCols = NULL,
            responseCol = NULL,
            weightsPath = "",
            weightsSep = "auto",
            missingStrategy = "mean",
            normalize = FALSE,
            showCoverage = TRUE,
            showScoreTable = TRUE,
            showDistPlot = TRUE,
            showPercentiles = TRUE,
            percentileBreaks = "20,40,60,80,90,95",
            showAssoc = TRUE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpPGS",
                requiresData=TRUE,
                ...)

            private$..idCol <- jmvcore::OptionVariable$new(
                "idCol",
                idCol,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..snpCols <- jmvcore::OptionVariables$new(
                "snpCols",
                snpCols,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..responseCol <- jmvcore::OptionVariable$new(
                "responseCol",
                responseCol,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..weightsPath <- jmvcore::OptionString$new(
                "weightsPath",
                weightsPath,
                default="")
            private$..weightsSep <- jmvcore::OptionList$new(
                "weightsSep",
                weightsSep,
                options=list(
                    "auto",
                    "comma",
                    "tab"),
                default="auto")
            private$..missingStrategy <- jmvcore::OptionList$new(
                "missingStrategy",
                missingStrategy,
                options=list(
                    "mean",
                    "zero",
                    "exclude"),
                default="mean")
            private$..normalize <- jmvcore::OptionBool$new(
                "normalize",
                normalize,
                default=FALSE)
            private$..showCoverage <- jmvcore::OptionBool$new(
                "showCoverage",
                showCoverage,
                default=TRUE)
            private$..showScoreTable <- jmvcore::OptionBool$new(
                "showScoreTable",
                showScoreTable,
                default=TRUE)
            private$..showDistPlot <- jmvcore::OptionBool$new(
                "showDistPlot",
                showDistPlot,
                default=TRUE)
            private$..showPercentiles <- jmvcore::OptionBool$new(
                "showPercentiles",
                showPercentiles,
                default=TRUE)
            private$..percentileBreaks <- jmvcore::OptionString$new(
                "percentileBreaks",
                percentileBreaks,
                default="20,40,60,80,90,95")
            private$..showAssoc <- jmvcore::OptionBool$new(
                "showAssoc",
                showAssoc,
                default=TRUE)

            self$.addOption(private$..idCol)
            self$.addOption(private$..snpCols)
            self$.addOption(private$..responseCol)
            self$.addOption(private$..weightsPath)
            self$.addOption(private$..weightsSep)
            self$.addOption(private$..missingStrategy)
            self$.addOption(private$..normalize)
            self$.addOption(private$..showCoverage)
            self$.addOption(private$..showScoreTable)
            self$.addOption(private$..showDistPlot)
            self$.addOption(private$..showPercentiles)
            self$.addOption(private$..percentileBreaks)
            self$.addOption(private$..showAssoc)
        }),
    active = list(
        idCol = function() private$..idCol$value,
        snpCols = function() private$..snpCols$value,
        responseCol = function() private$..responseCol$value,
        weightsPath = function() private$..weightsPath$value,
        weightsSep = function() private$..weightsSep$value,
        missingStrategy = function() private$..missingStrategy$value,
        normalize = function() private$..normalize$value,
        showCoverage = function() private$..showCoverage$value,
        showScoreTable = function() private$..showScoreTable$value,
        showDistPlot = function() private$..showDistPlot$value,
        showPercentiles = function() private$..showPercentiles$value,
        percentileBreaks = function() private$..percentileBreaks$value,
        showAssoc = function() private$..showAssoc$value),
    private = list(
        ..idCol = NA,
        ..snpCols = NA,
        ..responseCol = NA,
        ..weightsPath = NA,
        ..weightsSep = NA,
        ..missingStrategy = NA,
        ..normalize = NA,
        ..showCoverage = NA,
        ..showScoreTable = NA,
        ..showDistPlot = NA,
        ..showPercentiles = NA,
        ..percentileBreaks = NA,
        ..showAssoc = NA)
)

snpPGSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSResults",
    inherit = jmvcore::Group,
    active = list(
        coverageTable = function() private$.items[["coverageTable"]],
        summaryTable = function() private$.items[["summaryTable"]],
        scoreTable = function() private$.items[["scoreTable"]],
        percentileTable = function() private$.items[["percentileTable"]],
        assocTable = function() private$.items[["assocTable"]],
        distPlot = function() private$.items[["distPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Polygenic Score (PGS)",
                refs="SNPstats")
            self$add(jmvcore::Table$new(
                options=options,
                name="coverageTable",
                title="SNP Coverage Summary",
                visible="(showCoverage)",
                rows=1,
                columns=list(
                    list(
                        `name`="snpsInWeights", 
                        `title`="SNPs in weights file", 
                        `type`="integer"),
                    list(
                        `name`="snpsInData", 
                        `title`="SNPs in dataset", 
                        `type`="integer"),
                    list(
                        `name`="snpsMatched", 
                        `title`="Matched", 
                        `type`="integer"),
                    list(
                        `name`="pctMatched", 
                        `title`="% matched", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="snpsAmbiguous", 
                        `title`="Ambiguous (AT/CG)", 
                        `type`="integer"),
                    list(
                        `name`="missingStrategy", 
                        `title`="Missing strategy", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="PGS Summary Statistics",
                rows=1,
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="skew", 
                        `title`="Skewness", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="scoreTable",
                title="Per-Individual Scores",
                visible="(showScoreTable)",
                columns=list(
                    list(
                        `name`="individual", 
                        `title`="Individual", 
                        `type`="text"),
                    list(
                        `name`="pgs", 
                        `title`="PGS Score", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pgs_z", 
                        `title`="Z-score", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="percentile", 
                        `title`="Percentile", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showPercentiles)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="percentileTable",
                title="Percentile Thresholds",
                visible="(showPercentiles)",
                columns=list(
                    list(
                        `name`="threshold", 
                        `title`="Percentile", 
                        `type`="text"),
                    list(
                        `name`="score", 
                        `title`="PGS Score", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="assocTable",
                title="PGS\u2013Response Association",
                visible="(showAssoc)",
                rows=1,
                columns=list(
                    list(
                        `name`="responseVar", 
                        `title`="Response", 
                        `type`="text"),
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="beta", 
                        `title`="\u03B2 (or log-OR)", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="stat", 
                        `title`="Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="distPlot",
                title="Score Distribution",
                visible="(showDistPlot)",
                width=560,
                height=390,
                renderFun=".plotDist"))}))

snpPGSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpPGS",
                version = c(0,3,0),
                options = options,
                results = snpPGSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Polygenic Score (PGS)
#'
#' 
#' @param data [object Object]
#' @param idCol Column identifying each individual. Row numbers used if
#'   omitted.
#' @param snpCols One column per SNP. Dosage (0/1/2) or allele strings
#'   auto-detected per column.
#' @param responseCol Optional outcome variable. If provided, an association
#'   test between PGS and response is reported (logistic for binary, linear for
#'   continuous).
#' @param weightsPath Path to a PGS Catalog-format file with columns: rsID,
#'   effect_allele, effect_weight. Lines starting with '#' are skipped
#'   automatically.
#' @param weightsSep Column delimiter of the weights file.
#' @param missingStrategy Strategy for handling missing genotype values.
#' @param normalize If TRUE, divides each PGS by the number of matched SNPs.
#' @param showCoverage Show the SNP coverage summary table.
#' @param showScoreTable Show the per-individual PGS score table.
#' @param showDistPlot Show the score distribution histogram and density plot.
#' @param showPercentiles Show percentile ranks for each individual and
#'   threshold table.
#' @param percentileBreaks Comma-separated list of percentile thresholds for
#'   the threshold table.
#' @param showAssoc Show the PGS-response association table (requires a
#'   response variable to be selected).
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$coverageTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$percentileTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$assocTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$distPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$coverageTable$asDF}
#'
#' \code{as.data.frame(results$coverageTable)}
#'
#' @export
snpPGS <- function(
    data,
    idCol,
    snpCols,
    responseCol,
    weightsPath = "",
    weightsSep = "auto",
    missingStrategy = "mean",
    normalize = FALSE,
    showCoverage = TRUE,
    showScoreTable = TRUE,
    showDistPlot = TRUE,
    showPercentiles = TRUE,
    percentileBreaks = "20,40,60,80,90,95",
    showAssoc = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpPGS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(idCol)) idCol <- jmvcore::resolveQuo(jmvcore::enquo(idCol))
    if ( ! missing(snpCols)) snpCols <- jmvcore::resolveQuo(jmvcore::enquo(snpCols))
    if ( ! missing(responseCol)) responseCol <- jmvcore::resolveQuo(jmvcore::enquo(responseCol))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(idCol), idCol, NULL),
            `if`( ! missing(snpCols), snpCols, NULL),
            `if`( ! missing(responseCol), responseCol, NULL))


    options <- snpPGSOptions$new(
        idCol = idCol,
        snpCols = snpCols,
        responseCol = responseCol,
        weightsPath = weightsPath,
        weightsSep = weightsSep,
        missingStrategy = missingStrategy,
        normalize = normalize,
        showCoverage = showCoverage,
        showScoreTable = showScoreTable,
        showDistPlot = showDistPlot,
        showPercentiles = showPercentiles,
        percentileBreaks = percentileBreaks,
        showAssoc = showAssoc)

    analysis <- snpPGSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

