# snpPGS.R  — Public entry-point wrapper for SNPstats PGS analysis
# NOTE: This file must NOT define snpPGSBase (that is generated by jmvtools).
#       The public function must be named snpPGS to match the analysis name.

#' Polygenic Score (PGS) Calculator
#'
#' Part of the SNPstats jamovi module.
#'
#' @param data            Data frame. Rows = individuals, SNP columns in
#'                        dosage (0/1/2) or allele-string format.
#' @param snpCols         Character vector of SNP column names.
#' @param idCol           Name of the individual ID column (optional).
#' @param responseCol     Name of a binary or quantitative outcome column
#'                        for PGS association test (optional).
#' @param weightsPath     Path to PGS Catalog-format CSV/TSV weights file.
#' @param weightsSep      \code{"auto"}, \code{"comma"}, or \code{"tab"}.
#' @param missingStrategy \code{"mean"} (default), \code{"zero"}, or
#'                        \code{"exclude"}.
#' @param normalize       Logical. Divide score by matched SNP count.
#' @param showCoverage    Logical. Show SNP coverage summary table.
#' @param showScoreTable  Logical. Show per-individual score table.
#' @param showDistPlot    Logical. Show score distribution plot.
#' @param showPercentiles Logical. Show percentile ranks.
#' @param percentileBreaks Comma-separated percentile thresholds string.
#' @param showAssoc       Logical. Show PGS-response association table.
#'
#' @return A \code{snpPGSResults} object.
#'
#' @export
snpPGSBase <- function(
    data,
    snpCols,
    idCol             = NULL,
    responseCol       = NULL,
    weightsPath       = "",
    weightsSep        = "auto",
    missingStrategy   = "mean",
    normalize         = FALSE,
    showCoverage      = TRUE,
    showScoreTable    = TRUE,
    showDistPlot      = TRUE,
    showPercentiles   = TRUE,
    percentileBreaks  = "20,40,60,80,90,95",
    showAssoc         = TRUE
) {
    if (!requireNamespace("jmvcore", quietly = TRUE))
        stop("snpPGS requires jmvcore to be installed (restart may be required)")

    if (!missing(idCol))
        idCol <- jmvcore::resolveQuo(jmvcore::enquo(idCol))
    if (!missing(snpCols))
        snpCols <- jmvcore::resolveQuo(jmvcore::enquo(snpCols))
    if (!missing(responseCol))
        responseCol <- jmvcore::resolveQuo(jmvcore::enquo(responseCol))

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`(!missing(idCol),      idCol,      NULL),
            `if`(!missing(snpCols),    snpCols,    NULL),
            `if`(!missing(responseCol), responseCol, NULL))

    options <- snpPGSOptions$new(
        idCol            = idCol,
        snpCols          = snpCols,
        responseCol      = responseCol,
        weightsPath      = weightsPath,
        weightsSep       = weightsSep,
        missingStrategy  = missingStrategy,
        normalize        = normalize,
        showCoverage     = showCoverage,
        showScoreTable   = showScoreTable,
        showDistPlot     = showDistPlot,
        showPercentiles  = showPercentiles,
        percentileBreaks = percentileBreaks,
        showAssoc        = showAssoc)

    analysis <- snpPGSClass$new(options = options, data = data)
    analysis$run()
    analysis$results
}
