# snpPGS.b.R  — PGS analysis for SNPstats jamovi module
# Namespace: SNPstats
# Inherits from snpPGSBase (generated by jmvtools::prepare())

snpPGSClass <- R6::R6Class(
    "snpPGSClass",
    inherit = snpPGSBase,
    private = list(

        # ------------------------------------------------------------------ #
        #  Entry point                                                        #
        # ------------------------------------------------------------------ #
        .run = function() {
            opts <- self$options

            # ── Validate ───────────────────────────────────────────────── #
            if (length(opts$snpCols) == 0)
                jmvcore::reject("Please select at least one SNP column.")

            if (nchar(trimws(opts$weightsPath)) == 0)
                jmvcore::reject("Please provide the path to a weights file.")

            if (!file.exists(opts$weightsPath))
                jmvcore::reject(paste0(
                    "Weights file not found: '", opts$weightsPath, "'"))

            # ── Prepare genotype matrix ────────────────────────────────── #
            geno    <- private$.prepareGeno()
            snpMat  <- geno$snpMat
            ids     <- geno$ids

            # ── Load weights ───────────────────────────────────────────── #
            wt <- private$.loadWeights(opts$weightsPath, opts$weightsSep)

            # ── Match SNPs ─────────────────────────────────────────────── #
            matched   <- private$.matchSNPs(snpMat, wt)
            snpMatSub <- matched$snpMat
            wtVec     <- matched$weights

            # ── Coverage table ─────────────────────────────────────────── #
            if (opts$showCoverage) {
                ct <- self$results$coverageTable
                ct$setRow(rowNo = 1, values = list(
                    snpsInWeights   = nrow(wt),
                    snpsInData      = ncol(snpMat),
                    snpsMatched     = matched$nMatched,
                    pctMatched      = matched$nMatched / nrow(wt),
                    snpsAmbiguous   = matched$nAmbiguous,
                    missingStrategy = opts$missingStrategy
                ))
            }

            if (matched$nMatched == 0)
                jmvcore::reject(paste0(
                    "No SNPs matched between the selected columns and the ",
                    "weights file. Verify that column names use rsID format ",
                    "(e.g. rs12345)."))

            # ── Impute missing ─────────────────────────────────────────── #
            snpMatSub <- private$.imputeMissing(snpMatSub, opts$missingStrategy)

            # ── Calculate PGS ──────────────────────────────────────────── #
            scores <- as.numeric(snpMatSub %*% wtVec)
            if (opts$normalize) scores <- scores / matched$nMatched

            mu  <- mean(scores, na.rm = TRUE)
            sg  <- sd(scores,   na.rm = TRUE)
            zsc <- if (sg > 0) (scores - mu) / sg else rep(0, length(scores))
            pct <- 100 * rank(scores, ties.method = "average") / length(scores)

            # ── Summary table ──────────────────────────────────────────── #
            self$results$summaryTable$setRow(rowNo = 1, values = list(
                n    = length(scores),
                mean = mu,
                sd   = sg,
                min  = min(scores,  na.rm = TRUE),
                max  = max(scores,  na.rm = TRUE),
                skew = private$.skewness(scores)
            ))

            # ── Per-individual table ───────────────────────────────────── #
            if (opts$showScoreTable) {
                st <- self$results$scoreTable
                for (i in seq_along(scores)) {
                    st$addRow(rowKey = i, values = list(
                        individual = as.character(ids[i]),
                        pgs        = scores[i],
                        pgs_z      = zsc[i],
                        percentile = pct[i]
                    ))
                }
            }

            # ── Percentile threshold table ─────────────────────────────── #
            if (opts$showPercentiles) {
                breaks <- private$.parseBreaks(opts$percentileBreaks)
                pt <- self$results$percentileTable
                for (b in breaks) {
                    pt$addRow(rowKey = b, values = list(
                        threshold = paste0("P", b),
                        score     = as.numeric(
                            quantile(scores, b / 100, na.rm = TRUE))
                    ))
                }
            }

            # ── Association test ───────────────────────────────────────── #
            if (opts$showAssoc &&
                !is.null(opts$responseCol) &&
                nchar(opts$responseCol) > 0) {

                private$.runAssoc(scores, ids, opts$responseCol)
            }

            # ── Store state for plot ───────────────────────────────────── #
            self$results$distPlot$setState(
                list(scores = scores, mu = mu, sg = sg))
        },

        # ------------------------------------------------------------------ #
        #  Association test: PGS ~ response                                  #
        # ------------------------------------------------------------------ #
        .runAssoc = function(scores, ids, responseColName) {
            data     <- self$data
            response <- data[[responseColName]]

            # Align by row order (ids are row-indexed)
            nObs <- min(length(scores), length(response))
            df   <- data.frame(
                pgs      = scores[seq_len(nObs)],
                response = response[seq_len(nObs)]
            )
            df <- df[complete.cases(df), ]

            isBinary <- is.factor(df$response) ||
                        length(unique(na.omit(df$response))) == 2

            at <- self$results$assocTable

            tryCatch({
                if (isBinary) {
                    df$response <- as.numeric(as.factor(df$response)) - 1
                    fit  <- glm(response ~ pgs, data = df,
                                family = binomial(link = "logit"))
                    cf   <- summary(fit)$coefficients["pgs", ]
                    at$setRow(rowNo = 1, values = list(
                        responseVar = responseColName,
                        model       = "Logistic (binary)",
                        beta        = cf[1],
                        se          = cf[2],
                        stat        = cf[3],
                        p           = cf[4]
                    ))
                } else {
                    df$response <- as.numeric(df$response)
                    fit  <- lm(response ~ pgs, data = df)
                    cf   <- summary(fit)$coefficients["pgs", ]
                    at$setRow(rowNo = 1, values = list(
                        responseVar = responseColName,
                        model       = "Linear (continuous)",
                        beta        = cf[1],
                        se          = cf[2],
                        stat        = cf[3],
                        p           = cf[4]
                    ))
                }
            }, error = function(e) {
                jmvcore::warn(paste0(
                    "Association test failed: ", conditionMessage(e)))
            })
        },

        # ------------------------------------------------------------------ #
        #  Plot renderer                                                      #
        # ------------------------------------------------------------------ #
        .plotDist = function(image, ggtheme, theme, ...) {
            state <- image$state
            if (is.null(state)) return(FALSE)

            scores <- state$scores
            mu     <- state$mu
            sg     <- state$sg
            df     <- data.frame(pgs = scores)

            p <- ggplot2::ggplot(df, ggplot2::aes(x = pgs)) +

                ggplot2::geom_histogram(
                    ggplot2::aes(y = ggplot2::after_stat(density)),
                    bins    = max(10, min(50, floor(sqrt(length(scores))))),
                    fill    = "#4C7EBF",
                    colour  = "#2C5F9E",
                    alpha   = 0.75
                ) +

                ggplot2::geom_density(
                    colour    = "#E05C2A",
                    linewidth = 1.1
                ) +

                ggplot2::stat_function(
                    fun      = dnorm,
                    args     = list(mean = mu, sd = sg),
                    colour   = "#555555",
                    linewidth = 0.8,
                    linetype  = "dashed"
                ) +

                ggplot2::geom_vline(
                    xintercept = mu,
                    colour     = "#E05C2A",
                    linewidth  = 0.9
                ) +

                ggplot2::labs(
                    title    = "PGS Score Distribution",
                    subtitle = sprintf(
                        "N = %d  |  Mean = %.4f  |  SD = %.4f",
                        length(scores), mu, sg),
                    x       = "Polygenic Score",
                    y       = "Density",
                    caption = "Dashed: normal reference  |  Solid: kernel density"
                ) +

                ggtheme

            print(p)
            TRUE
        },

        # ------------------------------------------------------------------ #
        #  Helper: prepare genotype matrix from jamovi data                  #
        # ------------------------------------------------------------------ #
        .prepareGeno = function() {
            opts    <- self$options
            data    <- self$data
            snpCols <- opts$snpCols

            ids <- if (!is.null(opts$idCol) && nchar(opts$idCol) > 0)
                as.character(data[[opts$idCol]])
            else
                as.character(seq_len(nrow(data)))

            raw    <- as.data.frame(data[, snpCols, drop = FALSE])
            snpMat <- matrix(
                NA_real_,
                nrow     = nrow(raw),
                ncol     = ncol(raw),
                dimnames = list(ids, snpCols)
            )

            for (j in seq_along(snpCols))
                snpMat[, j] <- private$.toDosage(raw[[j]], snpCols[j])

            list(snpMat = snpMat, ids = ids)
        },

        # ------------------------------------------------------------------ #
        #  Helper: auto-detect encoding → numeric dosage 0/1/2               #
        # ------------------------------------------------------------------ #
        .toDosage = function(col, colName) {

            if (is.numeric(col)) {
                vals <- unique(na.omit(col))
                if (!all(vals %in% c(0, 1, 2)))
                    jmvcore::warn(paste0(
                        "Column '", colName,
                        "': numeric values outside {0,1,2}. Using as-is."))
                return(as.numeric(col))
            }

            col <- as.character(col)
            has_sep <- any(grepl("[/|]", na.omit(col)))

            if (has_sep) {
                return(sapply(strsplit(col, "[/|]"), function(p) {
                    if (length(p) != 2 || any(is.na(p))) return(NA_real_)
                    if (toupper(p[1]) == toupper(p[2])) return(2)
                    return(1)
                }))
            }

            # Two-char monolithic string e.g. "AT", "GG"
            sapply(col, function(x) {
                if (is.na(x) || nchar(x) != 2) return(NA_real_)
                if (substr(x, 1, 1) == substr(x, 2, 2)) return(2)
                return(1)
            }, USE.NAMES = FALSE)
        },

        # ------------------------------------------------------------------ #
        #  Helper: load PGS Catalog weights file                             #
        # ------------------------------------------------------------------ #
        .loadWeights = function(path, sepOpt) {
            sep <- switch(sepOpt,
                comma = ",",
                tab   = "\t",
                {
                    lines <- readLines(path, n = 30)
                    lines <- lines[!grepl("^#", lines)]
                    if (any(grepl("\t", lines))) "\t" else ","
                }
            )

            raw <- read.table(
                path,
                sep              = sep,
                header           = TRUE,
                comment.char     = "#",
                stringsAsFactors = FALSE,
                fill             = TRUE
            )
            names(raw) <- tolower(trimws(names(raw)))

            aliases <- list(
                rsid          = c("rsid", "snp", "variant_id", "snp_id",
                                  "id", "rs_id", "markername"),
                effect_allele = c("effect_allele", "a1", "allele1",
                                  "coded_allele", "alt"),
                effect_weight = c("effect_weight", "weight", "beta",
                                  "or", "effect_size", "score")
            )

            resolved <- list()
            for (field in names(aliases)) {
                col <- intersect(names(raw), aliases[[field]])[1]
                if (is.na(col))
                    jmvcore::reject(paste0(
                        "Weights file: column '", field, "' not found. ",
                        "Available: ", paste(names(raw), collapse = ", ")))
                resolved[[field]] <- col
            }

            wt <- data.frame(
                rsid          = toupper(trimws(raw[[resolved$rsid]])),
                effect_allele = toupper(trimws(raw[[resolved$effect_allele]])),
                effect_weight = as.numeric(raw[[resolved$effect_weight]]),
                stringsAsFactors = FALSE
            )
            wt[!is.na(wt$effect_weight), ]
        },

        # ------------------------------------------------------------------ #
        #  Helper: match columns to weights                                  #
        # ------------------------------------------------------------------ #
        .matchSNPs = function(snpMat, wt) {
            colsUpper <- toupper(colnames(snpMat))
            wtRsid    <- toupper(wt$rsid)

            ambig <- c("AT","TA","CG","GC")
            comp  <- c(A="T",T="A",C="G",G="C")
            nAmbiguous <- sum(
                paste0(wt$effect_allele,
                       comp[wt$effect_allele]) %in% ambig,
                na.rm = TRUE)

            idx  <- match(wtRsid, colsUpper)
            keep <- !is.na(idx)

            if (!any(keep))
                return(list(snpMat     = snpMat[, integer(0), drop = FALSE],
                            weights    = numeric(0),
                            nMatched   = 0L,
                            nAmbiguous = nAmbiguous))

            list(
                snpMat     = snpMat[, idx[keep], drop = FALSE],
                weights    = wt$effect_weight[keep],
                nMatched   = sum(keep),
                nAmbiguous = nAmbiguous
            )
        },

        # ------------------------------------------------------------------ #
        #  Helper: impute missing genotypes                                  #
        # ------------------------------------------------------------------ #
        .imputeMissing = function(mat, strategy) {
            if (!anyNA(mat)) return(mat)

            if (strategy == "exclude") {
                ok <- complete.cases(mat)
                if (!all(ok))
                    jmvcore::warn(paste0(
                        sum(!ok),
                        " individual(s) excluded due to missing genotypes."))
                return(mat[ok, , drop = FALSE])
            }

            for (j in seq_len(ncol(mat))) {
                na_j <- is.na(mat[, j])
                if (!any(na_j)) next
                mat[na_j, j] <- if (strategy == "mean")
                    mean(mat[, j], na.rm = TRUE) else 0
            }
            mat
        },

        # ------------------------------------------------------------------ #
        #  Helper: skewness                                                  #
        # ------------------------------------------------------------------ #
        .skewness = function(x) {
            x  <- x[!is.na(x)]
            n  <- length(x)
            mu <- mean(x)
            sg <- sd(x)
            if (sg == 0 || n < 3) return(NA_real_)
            (n / ((n-1)*(n-2))) * sum(((x - mu)/sg)^3)
        },

        # ------------------------------------------------------------------ #
        #  Helper: parse percentile breaks                                   #
        # ------------------------------------------------------------------ #
        .parseBreaks = function(str) {
            vals <- suppressWarnings(
                as.numeric(unlist(strsplit(str, "[,;[:space:]]+"))))
            vals <- sort(unique(vals[!is.na(vals) & vals > 0 & vals < 100]))
            if (length(vals) == 0) vals <- c(20, 40, 60, 80, 90, 95)
            vals
        }
    )
)
