
# This file is automatically generated, you probably don't want to edit this

weightedMeanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "weightedMeanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            propFile = "",
            weightDim = "weightX",
            tableOverrides = "{}", ...) {

            super$initialize(
                package="WeightedMean",
                name="weightedMean",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..propFile <- jmvcore::OptionString$new(
                "propFile",
                propFile,
                default="")
            private$..weightDim <- jmvcore::OptionList$new(
                "weightDim",
                weightDim,
                options=list(
                    "weightX",
                    "weightY",
                    "weightZ"),
                default="weightX")
            private$..tableOverrides <- jmvcore::OptionString$new(
                "tableOverrides",
                tableOverrides,
                default="{}")

            self$.addOption(private$..vars)
            self$.addOption(private$..propFile)
            self$.addOption(private$..weightDim)
            self$.addOption(private$..tableOverrides)
        }),
    active = list(
        vars = function() private$..vars$value,
        propFile = function() private$..propFile$value,
        weightDim = function() private$..weightDim$value,
        tableOverrides = function() private$..tableOverrides$value),
    private = list(
        ..vars = NA,
        ..propFile = NA,
        ..weightDim = NA,
        ..tableOverrides = NA)
)

weightedMeanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "weightedMeanResults",
    inherit = jmvcore::Group,
    active = list(
        matchInfo = function() private$.items[["matchInfo"]],
        propTableWidget = function() private$.items[["propTableWidget"]],
        results = function() private$.items[["results"]],
        overallResult = function() private$.items[["overallResult"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Weighted Mean with Property Table")
            self$add(jmvcore::Table$new(
                options=options,
                name="matchInfo",
                title="Variable Matching",
                clearWith=list(
                    "vars",
                    "propFile"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="matched", 
                        `title`="Matched in CSV", 
                        `type`="text"),
                    list(
                        `name`="weightX", 
                        `title`="Weight X", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="weightY", 
                        `title`="Weight Y", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="weightZ", 
                        `title`="Weight Z", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="propTableWidget",
                title="Variable Properties (Editable)",
                clearWith=list(
                    "vars",
                    "propFile")))
            self$add(jmvcore::Table$new(
                options=options,
                name="results",
                title="Weighted Mean Results",
                clearWith=list(
                    "vars",
                    "propFile",
                    "weightDim",
                    "tableOverrides"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Unweighted Mean", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="weightUsed", 
                        `title`="Weight Used", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="weightedMean", 
                        `title`="Weighted Mean", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="overallResult",
                title="Overall Weighted Mean (All Variables)",
                clearWith=list(
                    "vars",
                    "propFile",
                    "weightDim",
                    "tableOverrides"),
                columns=list(
                    list(
                        `name`="dimension", 
                        `title`="Dimension", 
                        `type`="text"),
                    list(
                        `name`="overallWeightedMean", 
                        `title`="Overall Weighted Mean", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

weightedMeanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "weightedMeanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "WeightedMean",
                name = "weightedMean",
                version = c(0,1,0),
                options = options,
                results = weightedMeanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Weighted Mean with Property Table
#'
#' Upload a CSV with variable weights (columns: Var, weightX, weightY, 
#' weightZ), select numeric variables from data, edit the property grid 
#' interactively, and compute weighted means per chosen weight dimension.
#' 
#' @param data the data as a data frame
#' @param vars numeric variables to include in the analysis
#' @param propFile Full path to the CSV file containing variable properties.
#'   Expected columns: Var, weightX, weightY, weightZ.
#' @param weightDim which weight column to use for the weighted mean
#'   calculation
#' @param tableOverrides JSON string storing user edits made in the
#'   interactive property grid. Written by the results panel via postMessage and
#'   read by R on each re-run to apply overrides before computation.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$matchInfo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$propTableWidget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$results} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$overallResult} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matchInfo$asDF}
#'
#' \code{as.data.frame(results$matchInfo)}
#'
#' @export
weightedMean <- function(
    data,
    vars,
    propFile = "",
    weightDim = "weightX",
    tableOverrides = "{}") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("weightedMean requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- weightedMeanOptions$new(
        vars = vars,
        propFile = propFile,
        weightDim = weightDim,
        tableOverrides = tableOverrides)

    analysis <- weightedMeanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

